% Enter the info of the subject
prompt      = {'N:';...
    'Name:';...
    'Gender:';...
    'Age:';...
    'Handness:';...
    'Languages:';...
    'Debug';...
    'DebugAudio';...
    'EEG';...
    'EyeTracker'};

defans      = {'99';...
    'xxx';...
    'f';...
    '25' ;...
    'r';...
    'n';...
    '0';...
    '0';...
    '0';...
    '0'};

answer = inputdlg(prompt,'Subject Info',1,defans);

E.sbj.n       = str2double(answer{1});
E.sbj.name    = answer{2};
E.sbj.gender  = answer{3};
E.sbj.age     = str2double(answer{4});
E.sbj.hand    = answer{5};
E.sbj.lang    = answer{6};
E.debugmode   = logical(str2double(answer{7}));
E.useEEG      = logical(str2double(answer{9}));
E.useET       = logical(str2double(answer{10}));